title: Iron
description: >-
  Iron is a fast and flexible middleware-oriented server framework that provides a small but robust foundation for creating complex applications and RESTful APIs. No middleware are bundled with Iron – instead, everything is drag-and-drop, allowing for ridiculously modular setups.
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
